=== johnhelmuth/cluster-map/data/schemas/characters/character.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://in-dire-straits.space/data/schemas/characters/character.schema.json",
  "title": "Character",
  "description": "A character in a Role Playing Game.",
  "type": "object",
  "properties": {
    "type": {
      "description": "The type of thingy the data describes, 'character'.",
      "type": "string",
      "const": "character"
    },
    "schemaVersion": {
      "description": "The version of the schema for the data.",
      "type": "string",
      "const": "1"
    },
    "id": {
      "title": "ID",
      "description": "Unique identifier for the character.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "The name of the character.",
      "type": "string"
    },
    "playerName": {
      "description": "The name of the player of the character.",
      "type": "string"
    },
    "campaigns": {
      "title": "Campaigns",
      "description": "A list of campaign IDs this character is in.",
      "type": "array",
      "items": {
        "type": "string",
        "title": "Campaign ID",
        "description": "The IDs of the campaigns the character is in."
      }
    },
    "description": {
      "description": "The description of the character, Markdown allowed.",
      "type": "string"
    },
    "characterType": {
      "title": "Character type",
      "description": "The type of character, PC, NPC, Mob, Ship, etc.",
      "type": "string",
      "enum": [
        "PC",
        "NPC",
        "ship",
        "mob"
      ]
    },
    "refresh": {
      "description": "The current minimum number of Fate points the player of this character starts with at the beginning of a session.",
      "type": "integer",
      "minimum": 1,
      "default": 3
    },
    "fatePoints": {
      "description": "The current number of Fate points the player of this character currently has.",
      "type": "integer",
      "minimum": 0,
      "default": 3
    },
    "aspects": {
      "description": "The Aspects describing the character.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "aspectType": {
            "description": "The type of Aspect",
            "type": "string",
            "enum": [
              "High Concept",
              "Trouble",
              "Relationship",
              "Reason to Race",
              "Oneshot Reason",
              "Other"
            ]
          },
          "name": {
            "description": "The name of the Aspect",
            "type": "string"
          },
          "description": {
            "description": "A description of the Aspect, giving a little more context, Markdown allowed.",
            "type": "string"
          },
          "freeInvokes": {
            "type": "number",
            "description": "How many Free Invokes are currently on the Aspect",
            "minimum": 0,
            "default": 0
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "images": {
      "description": "A list of images representing the character, to be included on the character's sheet.",
      "title": "Character Images",
      "type": "array",
      "items": {
        "description": "The details about an image.",
        "title": "Image",
        "type": "object",
        "properties": {
          "uri": {
            "type": "string",
            "description": "The URI of an image.",
            "title": "Image URI"
          },
          "caption": {
            "description": "The caption to be displayed with the image.",
            "title": "Image Caption",
            "type": "string"
          }
        },
        "required": [
          "uri"
        ]
      },
      "minItems": 1
    },
    "traitType": {
      "type": "string",
      "description": "The type of the properties of the character used as a bonus on a dice roll to resolve actions.",
      "enum": [
        "skill",
        "approach",
        "profession",
        "other"
      ]
    },
    "traits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the trait, like 'Notice', 'Careful', or 'Warrior'"
          },
          "rank": {
            "type": "integer",
            "description": "The bonus applied to a resolution roll when this trait is applicable.",
            "minimum": 0
          }
        },
        "required": [
          "name",
          "rank"
        ]
      }
    },
    "stunts": {
      "type": "array",
      "description": "A list of the stunts the character can use.",
      "items": {
        "$ref": "https://in-dire-straits.space/data/schemas/characters/stunt.schema.json"
      }
    },
    "tracks": {
      "type": "array",
      "description": "The data structures used to track the current state of the character.",
      "items": {
        "type": "object",
        "properties": {
          "trackId": {
            "type": "string",
            "description": "A unique identifier for this track on the character to which it is tied."
          },
          "trackLabel": {
            "type": "string",
            "description": "The label or title for this track."
          },
          "showSoakAmount": {
            "type": "boolean",
            "description": "Should the amount of soak the boxes in this track be displayed to the user?"
          },
          "boxes": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "isUsed": {
                  "type": "boolean",
                  "description": "Has the box been used to soak shifts of effect?"
                },
                "soakValue": {
                  "type": "number",
                  "description": "How many shifts of effect the box can soak."
                }
              },
              "required": [
                "isUsed",
                "soakValue"
              ]
            }
          },
          "aspect": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "The Aspect representing the consequence in this track."
              },
              "description": {
                "description": "A description of the Consequence Aspect, giving a little more context, Markdown allowed.",
                "type": "string"
              },
              "freeInvokes": {
                "type": "number",
                "description": "How many Free Invokes the consequence already has."
              },
              "state": {
                "type": "string",
                "enum": [
                  "free",
                  "used",
                  "recovering"
                ]
              }
            },
            "required": [
              "name",
              "freeInvokes",
              "state"
            ]
          }
        },
        "required": [
          "trackId"
        ]
      }
    },
    "notes": {
      "title": "Notes",
      "description": "Section for notes about the character",
      "type": "array",
      "items": {
        "description": "A line of a multi-text notes field. Supports Markdown",
        "type": "string"
      }
    },
    "tags": {
      "title": "Tags",
      "description": "Arbitrary tags to be applied to the character.",
      "type": "array",
      "items": {
        "title": "Tag",
        "description": "A tag that applies to a character.",
        "type": "string",
        "minLength": 2
      }
    }
  },
  "required": [
    "type",
    "schemaVersion",
    "id",
    "name"
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/crush-wilson.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "crush-wilson",
  "name": "\"Crush\" Wilson",
  "playerName": "Jon T.",
  "characterType": "PC",
  "description": "He's a Bearble with a taste for thrills and fixing things.",
  "campaigns": ["one-shot-1"],
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Surfer-Dude Bearble Engineer"
    },
    {
      "aspectType": "Trouble",
      "name": "The Girls in Every Port Have Unionized"
    },
    {
      "aspectType": "Reason to Race",
      "name": "I must ride the biggest wave"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Engineering",
      "rank": 5
    },
    {
      "name": "Pilot",
      "rank": 4
    },
    {
      "name": "Empathy",
      "rank": 4
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Stealth",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/templates/PC.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "XXXX",
  "name": "",
  "playerName": "",
  "description": "",
  "campaigns": [],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": ""
    },
    {
      "aspectType": "Trouble",
      "name": ""
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "",
      "rank": 4
    },
    {
      "name": "",
      "rank": 3
    },
    {
      "name": "",
      "rank": 3
    }
  ],
  "stunts": [
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "",
      "description": "",
      "mechanics": [
        {
          "mechanicType": "dice-roll",
          "parameters": {
            "trait": "",
            "modifier": 2,
            "actions": ["Overcome"],
            "modificationType": "roll"
          }
        }
      ]
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/templates/NPC.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "XXXX",
  "name": "",
  "description": "",
  "campaigns": [],
  "characterType": "NPC",
  "aspects": [
    {
      "name": ""
    }
  ],
  "traitType": "other",
  "traits": [
    {
      "name": "Good at",
      "rank": 2
    },
    {
      "name": "Bad at",
      "rank": 0
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/dr-ridley-caast.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "dr-ridley-caast",
  "name": "Dr. Ridley 6ad-Bayanul-Longshores-Swifttide aan Caast-Foundling, PhD",
  "playerName": "Bea",
  "description": "Grulvax raised by the Calcoran Schools, she wears a full body suit and tries not to freak other species out.",
  "campaigns": ["one-shot-4"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Soft-spoken Academic"
    },
    {
      "aspectType": "Trouble",
      "name": "Confidence Breaking Anxiety / Terrifying Visage"
    },
    {
      "aspectType": "Oneshot Reason",
      "name": "Linguistic and Cultural Sapientologist on loan from Longshore University's Terrestrial Sapientology department"
    },
    {
      "name": "Begrudging Mathematics Expert"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Academics",
      "rank": 4
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Empathy",
      "rank": 3
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "notes": [
    "Doctor Ridley aan Caast-Foundling is a Grulvaxian raised by Calcorans who found her egg aboard a derelict ship of unknown make drifting in the Bayanul system. While loved by her parents and siblings, Swifttide cultural norms and a lack of knowledge about her species caused her to develop anxieties over many of her innate behavioral urges and her physical appearance. While talented in mathematics, even by Calcoran standards, she chose not to go into banking and instead studied linguistics and the impact language evolution has on the societies that speak them.\n",
    "**Note well:** Dr aan Caast-Foundling has no idea what a Grulvaxian is, and believes that must be others out there, but has not been able to find out anything about them on the Tatternet.\n",
    "\n",
    "#### History",
    "* Studied the dead language of a lost colony Maaraat of Ohlzor and So'enela after noting the similarity with the glyphs on the ancient artifact discovered in the Glaorkg system.\n",
    "* Conversant in the language of the Ohlzor on the rediscovered planet Cothar III. Created the translator program to allow speakers of Galacticom to converse with the Cotharians.",
    "* Currently studying the cultures of Cothar III based in the city of Cabitar, and as a guest of the royal family of the kingdom of Cabitar."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/delilah-lands.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "delilah",
  "name": "Delilah \"Deli\" Lands",
  "playerName": "Bea",
  "description": "",
  "campaigns": ["campaign-2"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Transhuman Transgender Engineer",
      "description": "* Voice synth/modulation\n* Equipment compartments\n* Recording software\n* Advanced audio/visual sensors\n* Oxygen recycler\n* Integrated smart phone/computer for communications"
    },
    {
      "aspectType": "Trouble",
      "name": "Cyborg \"Menace\"",
      "description": "To be clear, Delilah is not a cyborg menace; she just has to deal with humans who think that she is."
    },
    {
      "name": "God Damn Chairs",
      "description": "Delilah's 10 foot long body does not allow her to be comfortable in most human sized spaces.\n\nFor example, Delilah must coil up in the cargo section of the space elevator when she travels the planet."
    },
    {
      "name": "Doesn't Hold Grudges"
    },
    {
      "name": "People Pleaser"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Engineering",
      "rank": 4
    },
    {
      "name": "Rapport",
      "rank": 3
    },
    {
      "name": "Notice",
      "rank": 3
    },
    {
      "name": "Physique",
      "rank": 2
    },
    {
      "name": "Empathy",
      "rank": 2
    },
    {
      "name": "Provoke",
      "rank": 2
    },
    {
      "name": "Shoot",
      "rank": 1
    },
    {
      "name": "Pilot",
      "rank": 1
    }
  ],
  "stunts": [
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Restraint Protocols",
      "description": "Because ***I have programmed my multiple robotic arms and other limbs to do so***, I can use _Engineering_ instead of _Fight_ to Grapple Opponents in a Conflict"
    },
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Cybernetic metal is tougher than your average bear",
      "description": "Because I have an enormous metal cybernetic body, I get an extra Mild (2) Consequence slot that can only be used for physical consequences.",
      "mechanics": [
        {
          "mechanicType": "add-consequence",
          "parameters": {
            "consequenceLevel": "mild",
            "trackLabel": "Mild (Phys)"
          }
        }
      ]
    },
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Self-Repair Protocol",
      "description": "Because ***I've engineered my own cyberbody with knowledge on how to fix itself***, I can reduce a moderate injury to a mild,"
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild (Phys)",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/avery-johnson.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "avery-johnson",
  "name": "Avery Johnson",
  "playerName": "Chance",
  "description": "Security for SMTF",
  "campaigns": [
    "one-shot-4"
  ],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Career Soldier"
    },
    {
      "aspectType": "Trouble",
      "name": "Thrill-seeker"
    },
    {
      "aspectType": "Oneshot Reason",
      "name": "To boldly go"
    }
  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Notice",
      "rank": 4
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Shoot",
      "rank": 3
    },
    {
      "name": "Rapport",
      "rank": 2
    },
    {
      "name": "Engineering",
      "rank": 2
    },
    {
      "name": "Physique",
      "rank": 2
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "stunts": [
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Prefers to disable",
      "description": "Because I ***Prefer to Disable*** my opponents, I get +2 to Shoot Attacks when I am using a gun to stun or otherwise not kill.",
      "mechanics": [
        {
          "mechanicType": "dice-roll",
          "parameters": {
            "trait": "Shoot",
            "modifier": 2,
            "actions": [
              "Attack"
            ],
            "modificationType": "roll"
          }
        }
      ]
    }
  ],
  "notes": [
    "#### Load out for Straitgate missions:",
    "* Laser Rifle",
    "* Pistol (Slugthrower, Semiautomatic)",
    "* Combat/Utility Knife",
    "* Body armour / vacuum ready",
    "* Chem-lights",
    "* Radio communication system integrated with body armour/vac-suit",
    "#### History",
    "Currently working security for the embassy and scientific mission on Cothar III, based in the city of Cabitar, and as a guest of the royal family of the kingdom of Cabitar."
  ]
}

=== johnhelmuth/cluster-map/data/characters/PCs/chris.json
{
  "type": "character",
  "schemaVersion": "1",
  "id": "chris",
  "name": "\"Chris\", of the Starfighter Chrysalis",
  "playerName": "Evan",
  "description": "A \"Thri-kreen\"-style ant-man. \n\nTwo feet worth of articulating black antennae covered with spines like tube-cleaning brushes. Brassy carapace moulted every few days. \n\nAnt-like face, black mandibles. Wide compound eyes, each lens a subtly different shade, sees in black-and-white at a wide angle. \n\nTwo true-arms from the shoulder, and two shorter footarms from the lower ribs. Two sets of joints on each limb. \n\nSimilarly oddly jointed lower limbs. (Lower locked to mimic human motions.) Vestigial wings (more nubs than anything)",
  "campaigns": ["campaign-1"],
  "characterType": "PC",
  "refresh": 3,
  "fatePoints": 3,
  "aspects": [
    {
      "aspectType": "High Concept",
      "name": "Escort Pilot From An Infamous Swarm Species"
    },
    {
      "aspectType": "Trouble",
      "name": "The Syndicate Sources the Substrates of My Pheromones"
    },
    {
      "name": "Craving Help On The Search For The Princess"
    },
    {
      "name": "No One Should Have To Face Danger Alone"
    },
    {
      "name": "Slow To Trust"
    }

  ],
  "traitType": "skill",
  "traits": [
    {
      "name": "Pilot",
      "rank": 4
    },
    {
      "name": "Fight",
      "rank": 3
    },
    {
      "name": "Athletics",
      "rank": 3
    },
    {
      "name": "Provoke",
      "rank": 2
    },
    {
      "name": "Notice",
      "rank": 2
    },
    {
      "name": "Physique",
      "rank": 2
    },
    {
      "name": "Academics",
      "rank": 1
    },
    {
      "name": "Engineering",
      "rank": 1
    },
    {
      "name": "Rapport",
      "rank": 1
    },
    {
      "name": "Will",
      "rank": 1
    },
    {
      "name": "Stealth",
      "rank": 1
    }
  ],
  "tracks": [
    {
      "trackId": "stress",
      "trackLabel": "Stress",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 1
        },
        {
          "isUsed": false,
          "soakValue": 2
        }
      ]
    },
    {
      "trackId": "consequence-mild",
      "trackLabel": "Mild",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 2
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-moderate",
      "trackLabel": "Moderate",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 4
        }
      ],
      "aspect": {
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    },
    {
      "trackId": "consequence-severe",
      "trackLabel": "Severe",
      "showSoakAmount": true,
      "boxes": [
        {
          "isUsed": false,
          "soakValue": 6
        }
      ],
      "aspect":{
        "name": "",
        "freeInvokes": 0,
        "state": "free"
      }
    }
  ],
  "stunts": [
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Specialist: Orbital Mechanics",
      "description": ""
    },
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Tough as Nails",
      "description": "Once per session, at the cost of a fate point, I can reduce the severity of a moderate consequence that's physical in nature to a mild consequence (if your mild consequence slot is free), or erase a mild consequence altogether."
    },
    {
      "schemaVersion": "1",
      "type":  "stunt",
      "name": "Inhaler of Soldier-Caste Pheromones",
      "description": "Once per scene, as a free action, can inhale a type of pheromone, and creates an Aspect like \"Fixated on [Soldier-Caste Priority]\""
    }
  ],
  "notes": [
    "Walks bipedally to put people at ease, quadrupedally on foot-arms when alone. A minimally patched, torn, gray, monochrome flight suit for the benefit of mammals identifying his role.",
    "",
    "Speaks in clicks and chirps, and sawing his antennae on each other to make noise. (Enjoys violins.)",
    "",
    "Flame-retardant somewhat-torn system-agnostic flight suit and jacket: minimally patched. Thinks it puts aliens at ease.",
    "",
    "Bandolier: Click-to-speech device + bags/slots for rip-bags, syringes, pheromone inhalers, stims + painkillers and epinephrine (for mammals).",
    "",
    "\"Am I missing the human element?\" check-phrase."
  ]
}
